### ISSUE TITLE
Interop case with no nonce, aad or plaintext

### ISSUE THREAD

**Issue by nmav** [dfoxfranke/libaes_siv#14]
When trying to test interoperability with an implementation for another lib, I stumbled on the case where N=0 (according to https://tools.ietf.org/html/rfc5297#section-2.4 ). That's the case where the key is used to encrypt zero data, zero AD, with no nonce. That follows a separate path in the pseudo code:
```
      S2V(K, S1, ..., Sn) {
        if n = 0 then
          return V = AES-CMAC(K, <one>)
        fi
```

With libaes_siv, I see the following:
```
key: fffefdfcfbfaf9f8f7f6f5f4f3f2f1f0f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
nonce,aad,plaintext zero
ciphertext: 499e3994710218de7582e0f2c0ab5ed0
```

With my implementation
```
key: fffefdfcfbfaf9f8f7f6f5f4f3f2f1f0f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
nonce,aad,plaintext zero
ciphertext: 949f99cbcc3eb5da6d3c45d0f59aa9c7
```
While I'm not complete sure that libaes_siv is wrong here, I see that in `AES_SIV_Init` CMAC operation is done on zero data, and not on the `<one>` vector that I would have expected according to rfc.

**Comment by dfoxfranke** [comment]
I think libaes_siv is doing the right thing here. S2V is a variadic function which takes a key plus zero-or-more `S` arguments. Any of those `S` arguments may be of zero length, but this is distinct from not providing those arguments at all.

When AES-SIV is used through the RFC 5116 interface, `N` is always 3: `S_1` is the associated data, `S_2` is the nonce, `S_3` is the plaintext. When libaes_siv is used through the low-level API documented in AES_SIV_Init.adoc, N can take on other values, depending on how many times you call `AES_SIV_AssociateData`. But the `plaintext` argument to `AES_SIV_EncryptFinal` is mandatory, therefore `N` is always at least 1 and the pseudocode case for `N=0` is not reachable.

**Comment by nmav** [comment]
> When AES-SIV is used through the RFC 5116 interface, N is always 3: S_1 is the associated data, S_2 is the nonce, S_3 is the plaintext.

Is that required by RFC5297 or by the libaes_siv implementation?

**Comment by dfoxfranke** [comment]
By RFC 5297.

>  Unfortunately, [RFC5116] restricts AD input to a single component and
   limits the benefit SIV offers for dealing in a natural fashion with
   AD consisting of multiple distinct components.  Therefore, when it is
   required to access SIV through the interface defined in [RFC5116], it
   is necessary to marshal multiple AD inputs into a single string (see
   Section 1.1) prior to invoking SIV.  Note that this requirement is
   not unique to SIV.  All cipher modes using [RFC5116] MUST similarly
   marshal multiple AD inputs into a single string, and any technique
   used for any other AEAD mode (e.g., a scatter/gather technique) can
   be used with SIV.

RFC 5297's RFC 5116 interface also sets N_MIN (minimum nonce length) to 1. In Feb 2017 I [pointed this out to the CFRG](https://mailarchive.ietf.org/arch/msg/cfrg/Gu5cyorHPLrQ_CGYe775Xc6SV1c) as a possible erratum but they decided against making any change.

**Comment by nmav** [comment]
Thank you. What is my understanding of it, is that nonce is always a single component (thus there can never be the `N=0` case which I mention above with such an API). However for AD, my reading of it is that AD cannot be multiple components; it is not apparent to me that the AD must be a single component when it is zero size. The "obvious" reading of it for me would be to skip the component when 0-size AD is provided. The same applies for the plaintext component, and that makes me think that RFC5297 is quite risky in terms of interoperability.

**Comment by dfoxfranke** [comment]
I agree that RFC 5297 needs clarification on the point, but I think your interpretation would lead to a security flaw. If you omit the AD argument to S2V when the AD has zero length, and likewise omit the P argument when the plaintext has zero length, then encrypting a plaintext of "foo" with an AD of "" would yield the same authenticator as encrypting a plaintext of "" with an AD of "foo" under the same key and nonce.

**Comment by randombit** [comment]
FWIW I just checked this and both Botan and OpenSSL's SIV agree with `libaes_siv`'s interpretation, 499e3994710218de7582e0f2c0ab5ed0

**Comment by dfoxfranke** [comment]
Closing this issue but feel free to continue the discussion.

**Comment by nmav** [comment]
That's not universal though. Another implementation gives another value: https://github.com/miscreant/miscreant/issues/194

What I take from it is that only the "AEAD mode" is unambiguous for this cipher.

**Comment by dfoxfranke** [comment]
I'm not seeing any disagreement with miscreant. The test vector you quote in that ticket contains no ADs or nonce and a zero-length (not absent) plaintext. When I run that case through libaes_siv it gives me the same "f2007a5b eb2b8900 c588a7ad f599f172" ciphertext that miscreant gets.

libaes_siv won't make it possible to test what `S2V(K, [])` gives you because it doesn't directly export an S2V function and there's no way to make it compute an S2V with an absent plaintext. The `if n = 0 then return V = AES-CMAC(K, <one>) fi` case isn't handled anywhere because it doesn't have to be.
